DROP TABLE IF EXISTS events;

CREATE TABLE events
(
id INTEGER NOT NULL AUTO_INCREMENT,
TIMESTAMP DATETIME,
event_type INTEGER,
quantity DECIMAL(7,2) DEFAULT NULL,
modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

INSERT INTO events (TIMESTAMP, event_type, quantity) VALUES (CURRENT_TIMESTAMP, 0, 0);
